import { SourceConfig } from "./types";
import { buildGoogleNewsSearchUrl } from "./utils";

const DIRECT_RSS_SOURCES: SourceConfig[] = [
    {
        id: "bbc-world",
        name: "BBC World",
        kind: "rss",
        sourceType: "rss",
        url: "https://feeds.bbci.co.uk/news/rss.xml",
        language: "en",
        category: "world",
        country: "gb",
        enabled: true,
    },
    {
        id: "bbc-business",
        name: "BBC Business",
        kind: "rss",
        sourceType: "rss",
        url: "https://feeds.bbci.co.uk/news/business/rss.xml",
        language: "en",
        category: "business",
        country: "gb",
        enabled: true,
    },
    {
        id: "bbc-tech",
        name: "BBC Technology",
        kind: "rss",
        sourceType: "rss",
        url: "https://feeds.bbci.co.uk/news/technology/rss.xml",
        language: "en",
        category: "technology",
        country: "gb",
        enabled: true,
    },
    {
        id: "reuters-world",
        name: "Reuters World",
        kind: "rss",
        sourceType: "rss",
        url: "https://feeds.reuters.com/Reuters/worldNews",
        language: "en",
        category: "world",
        country: "global",
        enabled: true,
    },
    {
        id: "reuters-business",
        name: "Reuters Business",
        kind: "rss",
        sourceType: "rss",
        url: "https://feeds.reuters.com/reuters/businessNews",
        language: "en",
        category: "business",
        country: "global",
        enabled: true,
    },
    {
        id: "reuters-technology",
        name: "Reuters Technology",
        kind: "rss",
        sourceType: "rss",
        url: "https://feeds.reuters.com/reuters/technologyNews",
        language: "en",
        category: "technology",
        country: "global",
        enabled: true,
    },
    {
        id: "guardian-world",
        name: "The Guardian World",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.theguardian.com/world/rss",
        language: "en",
        category: "world",
        country: "gb",
        enabled: true,
    },
    {
        id: "guardian-politics",
        name: "The Guardian Politics",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.theguardian.com/politics/rss",
        language: "en",
        category: "politics",
        country: "gb",
        enabled: true,
    },
    {
        id: "guardian-business",
        name: "The Guardian Business",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.theguardian.com/uk/business/rss",
        language: "en",
        category: "business",
        country: "gb",
        enabled: true,
    },
    {
        id: "guardian-tech",
        name: "The Guardian Technology",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.theguardian.com/uk/technology/rss",
        language: "en",
        category: "technology",
        country: "gb",
        enabled: true,
    },
    {
        id: "cnn-top",
        name: "CNN Top",
        kind: "rss",
        sourceType: "rss",
        url: "http://rss.cnn.com/rss/edition.rss",
        language: "en",
        category: "world",
        country: "us",
        enabled: true,
    },
    {
        id: "cnn-world",
        name: "CNN World",
        kind: "rss",
        sourceType: "rss",
        url: "http://rss.cnn.com/rss/edition_world.rss",
        language: "en",
        category: "world",
        country: "us",
        enabled: true,
    },
    {
        id: "cnn-business",
        name: "CNN Business",
        kind: "rss",
        sourceType: "rss",
        url: "http://rss.cnn.com/rss/money_latest.rss",
        language: "en",
        category: "business",
        country: "us",
        enabled: true,
    },
    {
        id: "cnbc-top",
        name: "CNBC Top",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
        language: "en",
        category: "markets",
        country: "us",
        enabled: true,
    },
    {
        id: "cnbc-world",
        name: "CNBC World",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.cnbc.com/id/100727362/device/rss/rss.html",
        language: "en",
        category: "world",
        country: "us",
        enabled: true,
    },
    {
        id: "cnbc-tech",
        name: "CNBC Technology",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.cnbc.com/id/19854910/device/rss/rss.html",
        language: "en",
        category: "technology",
        country: "us",
        enabled: true,
    },
    {
        id: "marketwatch-top",
        name: "MarketWatch Top",
        kind: "rss",
        sourceType: "rss",
        url: "http://feeds.marketwatch.com/marketwatch/topstories/",
        language: "en",
        category: "markets",
        country: "us",
        enabled: true,
    },
    {
        id: "marketwatch-marketpulse",
        name: "MarketWatch MarketPulse",
        kind: "rss",
        sourceType: "rss",
        url: "http://feeds.marketwatch.com/marketwatch/marketpulse/",
        language: "en",
        category: "markets",
        country: "us",
        enabled: true,
    },
    {
        id: "ft-home",
        name: "Financial Times Home",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.ft.com/?format=rss",
        language: "en",
        category: "finance",
        country: "gb",
        enabled: true,
    },
    {
        id: "ap-top",
        name: "AP Top",
        kind: "rss",
        sourceType: "rss",
        url: "https://apnews.com/hub/ap-top-news?output=rss",
        language: "en",
        category: "world",
        country: "us",
        enabled: true,
    },
    {
        id: "politico-top",
        name: "Politico Top",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.politico.com/rss/politicopicks.xml",
        language: "en",
        category: "politics",
        country: "us",
        enabled: true,
    },
    {
        id: "verge-top",
        name: "The Verge",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.theverge.com/rss/index.xml",
        language: "en",
        category: "technology",
        country: "us",
        enabled: true,
    },
    {
        id: "techcrunch-top",
        name: "TechCrunch",
        kind: "rss",
        sourceType: "rss",
        url: "https://techcrunch.com/feed/",
        language: "en",
        category: "technology",
        country: "us",
        enabled: true,
    },
    {
        id: "ars-top",
        name: "Ars Technica",
        kind: "rss",
        sourceType: "rss",
        url: "http://feeds.arstechnica.com/arstechnica/index",
        language: "en",
        category: "technology",
        country: "us",
        enabled: true,
    },
    {
        id: "coindesk-top",
        name: "CoinDesk",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
        language: "en",
        category: "crypto",
        country: "global",
        enabled: true,
    },
    {
        id: "cointelegraph-top",
        name: "Cointelegraph",
        kind: "rss",
        sourceType: "rss",
        url: "https://cointelegraph.com/rss",
        language: "en",
        category: "crypto",
        country: "global",
        enabled: true,
    },
    {
        id: "decrypt-top",
        name: "Decrypt",
        kind: "rss",
        sourceType: "rss",
        url: "https://decrypt.co/feed",
        language: "en",
        category: "crypto",
        country: "global",
        enabled: true,
    },
    {
        id: "upravda-top",
        name: "Ukrainska Pravda",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.pravda.com.ua/rss/",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "upravda-articles",
        name: "Ukrainska Pravda Articles",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.pravda.com.ua/rss/view_articles/",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "econ-pravda",
        name: "Ekonomichna Pravda",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.epravda.com.ua/rss/",
        language: "uk",
        category: "economy",
        country: "ua",
        enabled: true,
    },
    {
        id: "nv-top",
        name: "NV",
        kind: "rss",
        sourceType: "rss",
        url: "https://nv.ua/ukr/rss/all.xml",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "liga-top",
        name: "LIGA.net",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.liga.net/news/rss.xml",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "rbc-ua",
        name: "RBC Ukraine",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.rbc.ua/static/rss/all.ukr.rss.xml",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "tsn-top",
        name: "TSN",
        kind: "rss",
        sourceType: "rss",
        url: "https://tsn.ua/rss/full.rss",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "unian-top",
        name: "UNIAN",
        kind: "rss",
        sourceType: "rss",
        url: "https://www.unian.ua/rss/full.rss",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "hromadske-top",
        name: "Hromadske",
        kind: "rss",
        sourceType: "rss",
        url: "https://hromadske.ua/feeds/posts",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "babel-top",
        name: "Babel",
        kind: "rss",
        sourceType: "rss",
        url: "https://babel.ua/rss.xml",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "kyiv-independent",
        name: "The Kyiv Independent",
        kind: "rss",
        sourceType: "rss",
        url: "https://kyivindependent.com/feed/",
        language: "en",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "suspilne-top",
        name: "Suspilne",
        kind: "rss",
        sourceType: "rss",
        url: "https://suspilne.media/rss/all.rss",
        language: "uk",
        category: "ukraine",
        country: "ua",
        enabled: true,
    },
    {
        id: "ain-top",
        name: "AIN",
        kind: "rss",
        sourceType: "rss",
        url: "https://ain.ua/feed/",
        language: "uk",
        category: "technology",
        country: "ua",
        enabled: true,
    },
    {
        id: "devua-top",
        name: "dev.ua",
        kind: "rss",
        sourceType: "rss",
        url: "https://dev.ua/news/rss",
        language: "uk",
        category: "technology",
        country: "ua",
        enabled: true,
    },
    {
        id: "itc-top",
        name: "ITC.ua",
        kind: "rss",
        sourceType: "rss",
        url: "https://itc.ua/ua/feed/",
        language: "uk",
        category: "technology",
        country: "ua",
        enabled: true,
    },
    {
        id: "incrypted-top",
        name: "Incrypted",
        kind: "rss",
        sourceType: "rss",
        url: "https://incrypted.com/feed/",
        language: "uk",
        category: "crypto",
        country: "ua",
        enabled: true,
    },
    {
        id: "forklog-top",
        name: "ForkLog",
        kind: "rss",
        sourceType: "rss",
        url: "https://forklog.com/feed",
        language: "ru",
        category: "crypto",
        country: "global",
        enabled: true,
    },
];

type GoogleNewsQueryDef = {
    slug: string;
    query: string;
    category: SourceConfig["category"];
    language: string;
    country: string;
    hl: string;
    gl: string;
    ceid: string;
};

const GOOGLE_NEWS_QUERY_DEFS: GoogleNewsQueryDef[] = [
    { slug: "ukraine-general-en", query: "Ukraine", category: "ukraine", language: "en", country: "ua", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "ukraine-war-en", query: "Ukraine war", category: "war", language: "en", country: "ua", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "ukraine-politics-en", query: "Ukraine politics", category: "politics", language: "en", country: "ua", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "ukraine-economy-en", query: "Ukraine economy", category: "economy", language: "en", country: "ua", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "ukraine-business-en", query: "Ukraine business", category: "business", language: "en", country: "ua", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "ukraine-tech-en", query: "Ukraine technology", category: "technology", language: "en", country: "ua", hl: "en-US", gl: "US", ceid: "US:en" },

    { slug: "crypto-en", query: "crypto", category: "crypto", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "bitcoin-en", query: "bitcoin", category: "crypto", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "ethereum-en", query: "ethereum", category: "crypto", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "solana-en", query: "solana", category: "crypto", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "binance-en", query: "binance", category: "crypto", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "bybit-en", query: "bybit", category: "crypto", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },

    { slug: "finance-en", query: "finance", category: "finance", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "markets-en", query: "markets", category: "markets", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "stock-market-en", query: "stock market", category: "markets", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "forex-en", query: "forex", category: "finance", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "federal-reserve-en", query: "Federal Reserve", category: "finance", language: "en", country: "us", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "inflation-en", query: "inflation", category: "economy", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },

    { slug: "world-en", query: "world news", category: "world", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "politics-en", query: "politics", category: "politics", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "war-en", query: "war", category: "war", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "technology-en", query: "technology", category: "technology", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "ai-en", query: "artificial intelligence", category: "technology", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },
    { slug: "cybersecurity-en", query: "cybersecurity", category: "technology", language: "en", country: "global", hl: "en-US", gl: "US", ceid: "US:en" },

    { slug: "ukraine-general-uk", query: "Україна", category: "ukraine", language: "uk", country: "ua", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "ukraine-war-uk", query: "війна в Україні", category: "war", language: "uk", country: "ua", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "ukraine-politics-uk", query: "політика України", category: "politics", language: "uk", country: "ua", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "ukraine-economy-uk", query: "економіка України", category: "economy", language: "uk", country: "ua", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "ukraine-finance-uk", query: "фінанси України", category: "finance", language: "uk", country: "ua", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "ukraine-tech-uk", query: "технології Україна", category: "technology", language: "uk", country: "ua", hl: "uk", gl: "UA", ceid: "UA:uk" },

    { slug: "crypto-uk", query: "криптовалюта", category: "crypto", language: "uk", country: "global", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "bitcoin-uk", query: "біткоїн", category: "crypto", language: "uk", country: "global", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "ethereum-uk", query: "ефіріум", category: "crypto", language: "uk", country: "global", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "finance-uk", query: "фінанси", category: "finance", language: "uk", country: "global", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "markets-uk", query: "ринок акцій", category: "markets", language: "uk", country: "global", hl: "uk", gl: "UA", ceid: "UA:uk" },
    { slug: "technology-uk", query: "технології", category: "technology", language: "uk", country: "global", hl: "uk", gl: "UA", ceid: "UA:uk" },

    { slug: "ukraine-general-ru", query: "Украина", category: "ukraine", language: "ru", country: "ua", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "ukraine-war-ru", query: "война в Украине", category: "war", language: "ru", country: "ua", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "ukraine-politics-ru", query: "политика Украины", category: "politics", language: "ru", country: "ua", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "ukraine-economy-ru", query: "экономика Украины", category: "economy", language: "ru", country: "ua", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "crypto-ru", query: "криптовалюта", category: "crypto", language: "ru", country: "global", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "bitcoin-ru", query: "биткоин", category: "crypto", language: "ru", country: "global", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "finance-ru", query: "финансы", category: "finance", language: "ru", country: "global", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "markets-ru", query: "рынки", category: "markets", language: "ru", country: "global", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "technology-ru", query: "технологии", category: "technology", language: "ru", country: "global", hl: "ru", gl: "RU", ceid: "RU:ru" },
    { slug: "politics-ru", query: "политика", category: "politics", language: "ru", country: "global", hl: "ru", gl: "RU", ceid: "RU:ru" },
];

const GOOGLE_NEWS_VARIANTS = [
    { suffix: "24h", modifier: " when:1d" },
    { suffix: "7d", modifier: " when:7d" },
    { suffix: "intitle", modifier: " intitle:" },
    { suffix: "exact", modifier: " exact" },
];

function buildGoogleNewsSources(): SourceConfig[] {
    const output: SourceConfig[] = [];

    for (const def of GOOGLE_NEWS_QUERY_DEFS) {
        for (const variant of GOOGLE_NEWS_VARIANTS) {
            let query = def.query;

            if (variant.suffix === "24h") {
                query = `${def.query}${variant.modifier}`;
            } else if (variant.suffix === "7d") {
                query = `${def.query}${variant.modifier}`;
            } else if (variant.suffix === "intitle") {
                query = `intitle:${def.query}`;
            } else if (variant.suffix === "exact") {
                query = `"${def.query}"`;
            }

            output.push({
                id: `gn-${def.slug}-${variant.suffix}`,
                name: `Google News ${def.query} ${variant.suffix}`,
                kind: "rss",
                sourceType: "google-news",
                url: buildGoogleNewsSearchUrl(query, def.hl, def.gl, def.ceid),
                language: def.language,
                category: def.category,
                country: def.country,
                enabled: true,
                tags: [def.query],
            });
        }
    }

    return output;
}

export const ALL_NEWS_SOURCES: SourceConfig[] = [
    ...DIRECT_RSS_SOURCES,
    ...buildGoogleNewsSources(),
].filter((source) => source.enabled !== false);